cpu-bind=MASK - boba, task  0  0 [2774055]: mask 0xff00000000000000fe00000000010000 set
/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/data/healthy-ml/scratch/abinitha/ContrastiveLearningProj/contrastive.py:127: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  distance_matrix = torch.tensor(precompute_lca_distances(np.arange(len(contrastive_classes)), contrastive_classes, contrastive_class_to_id, class_tree), device=device)
0it [00:00, ?it/s]0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/data/healthy-ml/scratch/abinitha/ContrastiveLearningProj/contrastive.py", line 140, in <module>
    for i, batch in enumerate(tqdm(train_dataloader)):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               ^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
huggingface_hub.errors.GatedRepoError: Caught GatedRepoError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/huggingface_hub-0.26.3-py3.8.egg/huggingface_hub/utils/_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/datasets/imagenet-1k/resolve/4603483700ee984ea9debe3ddbfdeae86f6489eb/data/train_images_0.tar.gz

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/torch/utils/data/_utils/worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 33, in fetch
    data.append(next(self.dataset_iter))
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/datasets/iterable_dataset.py", line 2072, in __iter__
    yield from self._iter_pytorch()
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/datasets/iterable_dataset.py", line 1997, in _iter_pytorch
    for key, example in ex_iterable:
                        ^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/datasets/iterable_dataset.py", line 1260, in __iter__
    yield from self._iter()
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/datasets/iterable_dataset.py", line 1316, in _iter
    for key, example in iterator:
                        ^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/datasets/iterable_dataset.py", line 1683, in __iter__
    for key, example in self.ex_iterable:
                        ^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/datasets/iterable_dataset.py", line 199, in __iter__
    for key_example in islice(self.generate_examples_fn(**gen_kwags), shard_example_idx_start, None):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/.cache/huggingface/modules/datasets_modules/datasets/imagenet-1k/07900defe1ccf3404ea7e5e876a64ca41192f6c07406044771544ef1505831e8/imagenet-1k.py", line 100, in _generate_examples
    for path, file in archive:
                      ^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/datasets/utils/track.py", line 50, in __iter__
    for x in self.generator(*self.args):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/datasets/utils/file_utils.py", line 1342, in _iter_from_urlpath
    yield from cls._iter_tar(f)
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/datasets/utils/file_utils.py", line 1293, in _iter_tar
    stream = tarfile.open(fileobj=f, mode="r|*")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/tarfile.py", line 1866, in open
    stream = _Stream(name, filemode, comptype, fileobj, bufsize,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/tarfile.py", line 355, in __init__
    fileobj = _StreamProxy(fileobj)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/tarfile.py", line 583, in __init__
    self.buf = self.fileobj.read(BLOCKSIZE)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/datasets/utils/file_utils.py", line 826, in read_with_retries
    out = read(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/huggingface_hub-0.26.3-py3.8.egg/huggingface_hub/hf_file_system.py", line 757, in read
    return super().read(length)
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/fsspec/spec.py", line 1941, in read
    out = self.cache._fetch(self.loc, self.loc + length)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/fsspec/caching.py", line 234, in _fetch
    self.cache = self.fetcher(start, end)  # new block replaces old
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/huggingface_hub-0.26.3-py3.8.egg/huggingface_hub/hf_file_system.py", line 720, in _fetch_range
    hf_raise_for_status(r)
  File "/data/healthy-ml/scratch/abinitha/miniconda3/envs/contrastive/lib/python3.12/site-packages/huggingface_hub-0.26.3-py3.8.egg/huggingface_hub/utils/_http.py", line 423, in hf_raise_for_status
    raise _format(GatedRepoError, message, response) from e
huggingface_hub.errors.GatedRepoError: 403 Client Error. (Request ID: Root=1-675356fa-1c8bb9e346f43d2b523be5ab;0a5b270c-86a0-4672-bd7d-cd50231df43d)

Cannot access gated repo for url https://huggingface.co/datasets/imagenet-1k/resolve/4603483700ee984ea9debe3ddbfdeae86f6489eb/data/train_images_0.tar.gz.
Access to dataset ILSVRC/imagenet-1k is restricted and you are not in the authorized list. Visit https://huggingface.co/datasets/ILSVRC/imagenet-1k to ask for access.

